spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: dbuser
    password: dbpass
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
